#!/bin/bash

#Check if $PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: Environment variable \$PYFILE is not set."
    exit 1
fi

#Check if the file exists
if [ ! -f "$PYFILE" ]; then
    echo "Error: File '$PYFILE' not found."
    exit 1
fi

# Run the Python script
python3 "$PYFILE"
